vcom 000-Log2.vhd
vcom 001-globals.vhd
vcom a.a-CU_HW.vhd
vcom a.c-IRAM.vhd
vcom a.b-DataPath.core/a.b.a-mux21.vhd
vcom a.b-DataPath.core/a.b.b-adder.vhd
vcom a.b-DataPath.core/a.b.c-register.vhd
vcom a.b-DataPath.core/a.b.d-ALU.vhd
vcom a.b-DataPath.core/a.b.d.a-NAND3.vhd
vcom a.b-DataPath.core/a.b.d.b-NAND4.vhd
vcom a.b-DataPath.core/a.b.d.c-Shifter.vhd
vcom a.b-DataPath.core/a.b.e-branching_unit.vhd
vcom a.b-DataPath.core/a.b.f-extender.vhd
vcom a.b-DataPath.core/a.b.g-mem.vhd
vcom a.b-DataPath.core/a.b.h-registerfile.vhd
vcom a.b-DataPath.vhd
vcom a-DLX.vhd
vcom test_bench/TB_DLX.vhd
