vcom 002-Log2.vhd
vcom 000-globals.vhd
vcom 001-generic_shifter.vhd
vcom a.a-CU_HW.vhd
vcom a.c-IRAM.vhd
vcom a.b-DataPath.core/a.b.a-ALU.vhd
vcom a.b-DataPath.core/a.b.a-NAND3.vhd
vcom a.b-DataPath.core/a.b.a-NAND4.vhd
vcom a.b-DataPath.core/a.b.b-Shifter.vhd
vcom a.b-DataPath.core/a.b.c-adder.vhd
vcom a.b-DataPath.core/a.b.c-extender.vhd
vcom a.b-DataPath.core/a.b.c-mem.vhd
vcom a.b-DataPath.core/a.b.c-mux21.vhd
vcom a.b-DataPath.core/a.b.c-register.vhd
vcom a.b-DataPath.core/a.b.c-registerfile.vhd
vcom a.b-DataPath.core/a.b.c-branching_unit.vhd
vcom a.b-DataPath.vhd
vcom a-DLX.vhd
