../DLX_vhd/000-Log2.vhd
../DLX_vhd/001-globals.vhd
../DLX_vhd/a.a-CU_HW.vhd
../DLX_vhd/a.c-IRAM.vhd
../DLX_vhd/a.b-DataPath.core/a.b.a-mux21.vhd
../DLX_vhd/a.b-DataPath.core/a.b.b-adder.vhd
../DLX_vhd/a.b-DataPath.core/a.b.c-register.vhd
../DLX_vhd/a.b-DataPath.core/a.b.d-ALU.vhd
../DLX_vhd/a.b-DataPath.core/a.b.d.a-NAND3.vhd
../DLX_vhd/a.b-DataPath.core/a.b.d.b-NAND4.vhd
../DLX_vhd/a.b-DataPath.core/a.b.d.c-Shifter.vhd
../DLX_vhd/a.b-DataPath.core/a.b.e-branching_unit.vhd
../DLX_vhd/a.b-DataPath.core/a.b.f-extender.vhd
../DLX_vhd/a.b-DataPath.core/a.b.g-mem.vhd
../DLX_vhd/a.b-DataPath.core/a.b.h-registerfile.vhd
../DLX_vhd/a.b-DataPath.vhd
../DLX_vhd/a-DLX.vhd
