../DLX_vhd/002-Log2.vhd
../DLX_vhd/000-globals.vhd
../DLX_vhd/001-generic_shifter.vhd
../DLX_vhd/a.c-IRAM.vhd
../DLX_vhd/a.b-DataPath.core/a.b.a-ALU.vhd
../DLX_vhd/a.b-DataPath.core/a.b.a-NAND3.vhd
../DLX_vhd/a.b-DataPath.core/a.b.a-NAND4.vhd
../DLX_vhd/a.b-DataPath.core/a.b.b-Shifter.vhd
../DLX_vhd/a.b-DataPath.core/a.b.c-adder.vhd
../DLX_vhd/a.b-DataPath.core/a.b.c-extender.vhd
../DLX_vhd/a.b-DataPath.core/a.b.c-mem.vhd
../DLX_vhd/a.b-DataPath.core/a.b.c-mux21.vhd
../DLX_vhd/a.b-DataPath.core/a.b.c-register.vhd
../DLX_vhd/a.b-DataPath.core/a.b.c-registerfile.vhd
../DLX_vhd/a.b-DataPath.core/a.b.c-branching_unit.vhd
../DLX_vhd/a.b-DataPath.vhd
../DLX_vhd/a.a-CU_HW.vhd
../DLX_vhd/a-DLX.vhd
